stages:
  - build
#  - upload
#  - deploy

build_job:
  image: docker
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - app/*
        - app/**/*
  script:
    - docker compose build

#upload:
#  stage: upload
#  script:
#    - docker push app:latest app/

#deploy:
#  stage: deploy
#  environment:
#    name: production
#  script:
#    - kubectl get pods